#:schema node_modules/wrangler/config-schema.json
name = "authjs-on-cloudflare-example"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
